# country_data.py

COUNTRY_INFO = {
    "afghanistan": {"code": "af"},
    "albania": {"code": "al"},
    "algeria": {"code": "dz"},
    "andorra": {"code": "ad"},
    "angola": {"code": "ao"},
    "argentina": {"code": "ar"},
    "armenia": {"code": "am"},
    "australia": {"code": "au"},
    "austria": {"code": "at"},
    "azerbaijan": {"code": "az"},
    "bahamas": {"code": "bs"},
    "bahrain": {"code": "bh"},
    "bangladesh": {"code": "bd"},
    "barbados": {"code": "bb"},
    "belarus": {"code": "by"},
    "belgium": {"code": "be"},
    "belize": {"code": "bz"},
    "benin": {"code": "bj"},
    "bhutan": {"code": "bt"},
    "bolivia": {"code": "bo"},
    "bosnia_and_herzegovina": {"code": "ba", "display_name": "bosnia and herzegovina"},
    "botswana": {"code": "bw"},
    "brazil": {"code": "br"},
    "brunei": {"code": "bn"},
    "bulgaria": {"code": "bg"},
    "burkina_faso": {"code": "bf", "display_name": "burkina faso"},
    "burundi": {"code": "bı"},
    "cabo_verde": {"code": "cv", "display_name": "cabo verde"},
    "cambodia": {"code": "kh"},
    "cameroon": {"code": "cm"},
    "canada": {"code": "ca"},
    "central_african_republic": {"code": "cf", "display_name": "central african republic"},
    "chad": {"code": "td"},
    "chile": {"code": "cl"},
    "china": {"code": "cn"}, # youtube'da çin için doğrudan trend verisi kısıtlı olabilir
    "colombia": {"code": "co"},
    "comoros": {"code": "km"},
    "congo_democratic_republicofthe": {"code": "cd", "display_name": "congo (democratic republic of the)"},
    "congo_republic_of_the": {"code": "cg", "display_name": "congo (republic of the)"},
    "costa_rica": {"code": "cr", "display_name": "costa rica"},
    "cote_dıvoire": {"code": "cı", "display_name": "cote d'ıvoire"},
    "croatia": {"code": "hr"},
    "cuba": {"code": "cu"}, # youtube'da küba için doğrudan trend verisi kısıtlı olabilir
    "cyprus": {"code": "cy"},
    "czech_republic": {"code": "cz", "display_name": "czech republic"},
    "denmark": {"code": "dk"},
    "djibouti": {"code": "dj"},
    "dominica": {"code": "dm"},
    "dominican_republic": {"code": "do", "display_name": "dominican republic"},
    "east_timor": {"code": "tl", "display_name": "east timor"},
    "ecuador": {"code": "ec"},
    "egypt": {"code": "eg"},
    "elsalvador": {"code": "sv", "display_name": "el salvador"},
    "equatorial_guinea": {"code": "gq", "display_name": "equatorial guinea"},
    "eritrea": {"code": "er"},
    "estonia": {"code": "ee"},
    "eswatini": {"code": "sz"},
    "ethiopia": {"code": "et"},
    "fiji": {"code": "fj"},
    "finland": {"code": "fı"},
    "france": {"code": "fr"},
    "gabon": {"code": "ga"},
    "gambia": {"code": "gm"},
    "georgia": {"code": "ge"},
    "germany": {"code": "de"},
    "ghana": {"code": "gh"},
    "greece": {"code": "gr"},
    "grenada": {"code": "gd"},
    "guatemala": {"code": "gt"},
    "guinea": {"code": "gn"},
    "guinea_bissau": {"code": "gw", "display_name": "guinea-bissau"},
    "guyana": {"code": "gy"},
    "haiti": {"code": "ht"},
    "honduras": {"code": "hn"},
    "hungary": {"code": "hu"},
    "ıceland": {"code": "ıs"},
    "ındia": {"code": "ın"},
    "ındonesia": {"code": "ıd"},
    "ıran": {"code": "ır"}, # youtube'da iran için doğrudan trend verisi kısıtlı olabilir
    "ıraq": {"code": "ıq"},
    "ıreland": {"code": "ıe"},
    "ısrael": {"code": "ıl"},
    "ıtaly": {"code": "ıt"},
    "jamaica": {"code": "jm"},
    "japan": {"code": "jp"},
    "jordan": {"code": "jo"},
    "kazakhstan": {"code": "kz"},
    "kenya": {"code": "ke"},
    "kiribati": {"code": "kı"},
    "korea_north": {"code": "kp", "display_name": "korea (north)"}, # youtube'da kuzey kore için doğrudan trend verisi kısıtlı olabilir
    "korea_south": {"code": "kr", "display_name": "korea (south)"},
    "kosovo": {"code": "xk", "display_name": "kosovo"}, # ıso 3166-1 alpha-2 standardına dahil değil, dikkat
    "kuwait": {"code": "kw"},
    "kyrgyzstan": {"code": "kg"},
    "laos": {"code": "la"},
    "latvia": {"code": "lv"},
    "lebanon": {"code": "lb"},
    "lesotho": {"code": "ls"},
    "liberia": {"code": "lr"},
    "libya": {"code": "ly"},
    "liechtenstein": {"code": "lı"},
    "lithuania": {"code": "lt"},
    "luxembourg": {"code": "lu"},
    "madagascar": {"code": "mg"},
    "malawi": {"code": "mw"},
    "malaysia": {"code": "my"},
    "maldives": {"code": "mv"},
    "mali": {"code": "ml"},
    "malta": {"code": "mt"},
    "marshall_ıslands": {"code": "mh", "display_name": "marshall ıslands"},
    "mauritania": {"code": "mr"},
    "mauritius": {"code": "mu"},
    "mexico": {"code": "mx"},
    "micronesia": {"code": "fm"},
    "moldova": {"code": "md"},
    "monaco": {"code": "mc"},
    "mongolia": {"code": "mn"},
    "montenegro": {"code": "me"},
    "morocco": {"code": "ma"},
    "mozambique": {"code": "mz"},
    "myanmar": {"code": "mm"},
    "namibia": {"code": "na"},
    "nauru": {"code": "nr"},
    "nepal": {"code": "np"},
    "netherlands": {"code": "nl"},
    "new_zealand": {"code": "nz", "display_name": "new zealand"},
    "nicaragua": {"code": "nı"},
    "niger": {"code": "ne"},
    "nigeria": {"code": "ng"},
    "north_macedonia": {"code": "mk", "display_name": "north macedonia"},
    "norway": {"code": "no"},
    "oman": {"code": "om"},
    "pakistan": {"code": "pk"},
    "palau": {"code": "pw"},
    "palestine": {"code": "ps"},
    "panama": {"code": "pa"},
    "papua_new_guinea": {"code": "pg", "display_name": "papua new guinea"},
    "paraguay": {"code": "py"},
    "peru": {"code": "pe"},
    "philippines": {"code": "ph"},
    "poland": {"code": "pl"},
    "portugal": {"code": "pt"},
    "qatar": {"code": "qa"},
    "romania": {"code": "ro"},
    "russia": {"code": "ru"},
    "rwanda": {"code": "rw"},
    "saint_kitts_and_nevis": {"code": "kn", "display_name": "saint kitts and nevis"},
    "saint_lucia": {"code": "lc", "display_name": "saint lucia"},
    "saint_vincent_and_the_grenadines": {"code": "vc", "display_name": "saint vincent and the grenadines"},
    "samoa": {"code": "ws"},
    "san_marino": {"code": "sm", "display_name": "san marino"},
    "sao_tome_and_principe": {"code": "st", "display_name": "sao tome and principe"},
    "saudi_arabia": {"code": "sa", "display_name": "saudi arabia"},
    "senegal": {"code": "sn"},
    "serbia": {"code": "rs"},
    "seychelles": {"code": "sc"},
    "sierra_leone": {"code": "sl", "display_name": "sierra leone"},
    "singapore": {"code": "sg"},
    "slovakia": {"code": "sk"},
    "slovenia": {"code": "sı"},
    "solomon_ıslands": {"code": "sb", "display_name": "solomon ıslands"},
    "somalia": {"code": "so"},
    "south_africa": {"code": "za", "display_name": "south africa"},
    "south_sudan": {"code": "ss", "display_name": "south sudan"},
    "spain": {"code": "es"},
    "sri_lanka": {"code": "lk", "display_name": "sri lanka"},
    "sudan": {"code": "sd"},
    "suriname": {"code": "sr"},
    "sweden": {"code": "se"},
    "switzerland": {"code": "ch"},
    "syria": {"code": "sy"},
    "taiwan": {"code": "tw"},
    "tajikistan": {"code": "tj"},
    "tanzania": {"code": "tz"},
    "thailand": {"code": "th"},
    "togo": {"code": "tg"},
    "tonga": {"code": "to"},
    "trinidad_and_tobago": {"code": "tt", "display_name": "trinidad and tobago"},
    "tunisia": {"code": "tn"},
    "turkey": {"code": "tr"},
    "turkmenistan": {"code": "tm"},
    "tuvalu": {"code": "tv"},
    "uganda": {"code": "ug"},
    "ukraine": {"code": "ua"},
    "united_arab_emirates": {"code": "ae", "display_name": "united arab emirates"},
    "united_kingdom": {"code": "gb", "display_name": "united kingdom"},
    "united_states": {"code": "us", "display_name": "united states"},
    "uruguay": {"code": "uy"},
    "uzbekistan": {"code": "uz"},
    "vanuatu": {"code": "vu"},
    "vatican_city": {"code": "va", "display_name": "vatican city"},
    "venezuela": {"code": "ve"},
    "vietnam": {"code": "vn"},
    "yemen": {"code": "ye"},
    "zambia": {"code": "zm"},
    "zimbabwe": {"code": "zw"}
}

# kıta bazlı ülke listeleri (apı'dan veri çekiminde kıta yerine ülke kodu kullanılacak)
# bu sadece navbarda veya listelemede kıta isimlerini kullanmak için bir mantıksal gruplama.
# apı isteği her zaman ülke kodu üzerinden yapılacaktır.
CONTINENT_COUNTRIES = {
    "asia": [
        "afghanistan", "armenia", "azerbaijan", "bahrain", "bangladesh", "bhutan", "brunei", "cambodia", "china", "cyprus", "east_timor", "georgia", "ındia", "ındonesia", "ıran", "ıraq", "ısrael", "japan", "jordan", "kazakhstan", "kiribati", "korea_north", "korea_south", "kuwait", "kyrgyzstan", "laos", "lebanon", "malaysia", "maldives", "mongolia", "myanmar", "nepal", "oman", "pakistan", "palestine", "philippines", "qatar", "saudi_arabia", "singapore", "sri_lanka", "syria", "taiwan", "tajikistan", "thailand", "turkey", "turkmenistan", "united_arab_emirates", "uzbekistan", "vietnam", "yemen"
    ],
    "europe": [
        "albania", "andorra", "austria", "belarus", "belgium", "bosnia_and_herzegovina", "bulgaria", "croatia", "czech_republic", "denmark", "estonia", "finland", "france", "germany", "greece", "hungary", "ıceland", "ıreland", "ıtaly", "kosovo", "latvia", "liechtenstein", "lithuania", "luxembourg", "malta", "moldova", "monaco", "montenegro", "netherlands", "north_macedonia", "norway", "poland", "portugal", "romania", "russia", "san_marino", "serbia", "slovakia", "slovenia", "spain", "sweden", "switzerland", "ukraine", "united_kingdom", "vatican_city"
    ],
    "africa": [
        "algeria", "angola", "benin", "botswana", "burkina_faso", "burundi", "cabo_verde", "cameroon", "central_african_republic", "chad", "comoros", "congo_democratic_republicofthe", "congo_republic_of_the", "cote_dıvoire", "djibouti", "egypt", "equatorial_guinea", "eritrea", "eswatini", "ethiopia", "gabon", "gambia", "ghana", "guinea", "guinea_bissau", "kenya", "lesotho", "liberia", "libya", "madagascar", "malawi", "mali", "mauritania", "mauritius", "morocco", "mozambique", "namibia", "niger", "nigeria", "rwanda", "sao_tome_and_principe", "senegal", "seychelles", "sierra_leone", "somalia", "south_africa", "south_sudan", "sudan", "tanzania", "togo", "tunisia", "uganda", "zambia", "zimbabwe"
    ],
    "north_america": [
        "antigua_and_barbuda", "bahamas", "barbados", "belize", "canada", "costa_rica", "cuba", "dominica", "dominican_republic", "elsalvador", "grenada", "guatemala", "haiti", "honduras", "jamaica", "mexico", "nicaragua", "panama", "saint_kitts_and_nevis", "saint_lucia", "saint_vincent_and_the_grenadines", "trinidad_and_tobago", "united_states"
    ],
    "south_america": [
        "argentina", "bolivia", "brazil", "chile", "colombia", "ecuador", "guyana", "paraguay", "peru", "suriname", "uruguay", "venezuela"
    ],
    "oceania": [
        "australia", "fiji", "kiribati", "marshall_ıslands", "micronesia", "nauru", "new_zealand", "palau", "papua_new_guinea", "samoa", "solomon_ıslands", "tonga", "tuvalu", "vanuatu"
    ]
}
