# country_data.py

COUNTRY_INFO = {
    "Afghanistan": {"code": "AF"},
    "Albania": {"code": "AL"},
    "Algeria": {"code": "DZ"},
    "Andorra": {"code": "AD"},
    "Angola": {"code": "AO"},
    "Argentina": {"code": "AR"},
    "Armenia": {"code": "AM"},
    "Australia": {"code": "AU"},
    "Austria": {"code": "AT"},
    "Azerbaijan": {"code": "AZ"},
    "Bahamas": {"code": "BS"},
    "Bahrain": {"code": "BH"},
    "Bangladesh": {"code": "BD"},
    "Barbados": {"code": "BB"},
    "Belarus": {"code": "BY"},
    "Belgium": {"code": "BE"},
    "Belize": {"code": "BZ"},
    "Benin": {"code": "BJ"},
    "Bhutan": {"code": "BT"},
    "Bolivia": {"code": "BO"},
    "Bosnia_And_Herzegovina": {"code": "BA", "display_name": "Bosnia and Herzegovina"},
    "Botswana": {"code": "BW"},
    "Brazil": {"code": "BR"},
    "Brunei": {"code": "BN"},
    "Bulgaria": {"code": "BG"},
    "Burkina_Faso": {"code": "BF", "display_name": "Burkina Faso"},
    "Burundi": {"code": "BI"},
    "Cabo_Verde": {"code": "CV", "display_name": "Cabo Verde"},
    "Cambodia": {"code": "KH"},
    "Cameroon": {"code": "CM"},
    "Canada": {"code": "CA"},
    "Central_African_Republic": {"code": "CF", "display_name": "Central African Republic"},
    "Chad": {"code": "TD"},
    "Chile": {"code": "CL"},
    "China": {"code": "CN"}, # YouTube'da Çin için doğrudan trend verisi kısıtlı olabilir
    "Colombia": {"code": "CO"},
    "Comoros": {"code": "KM"},
    "Congo_Democratic_RepublicOfThe": {"code": "CD", "display_name": "Congo (Democratic Republic of the)"},
    "Congo_Republic_Of_The": {"code": "CG", "display_name": "Congo (Republic of the)"},
    "Costa_Rica": {"code": "CR", "display_name": "Costa Rica"},
    "Cote_DIvoire": {"code": "CI", "display_name": "Cote d'Ivoire"},
    "Croatia": {"code": "HR"},
    "Cuba": {"code": "CU"}, # YouTube'da Küba için doğrudan trend verisi kısıtlı olabilir
    "Cyprus": {"code": "CY"},
    "Czech_Republic": {"code": "CZ", "display_name": "Czech Republic"},
    "Denmark": {"code": "DK"},
    "Djibouti": {"code": "DJ"},
    "Dominica": {"code": "DM"},
    "Dominican_Republic": {"code": "DO", "display_name": "Dominican Republic"},
    "East_Timor": {"code": "TL", "display_name": "East Timor"},
    "Ecuador": {"code": "EC"},
    "Egypt": {"code": "EG"},
    "ElSalvador": {"code": "SV", "display_name": "El Salvador"},
    "Equatorial_Guinea": {"code": "GQ", "display_name": "Equatorial Guinea"},
    "Eritrea": {"code": "ER"},
    "Estonia": {"code": "EE"},
    "Eswatini": {"code": "SZ"},
    "Ethiopia": {"code": "ET"},
    "Fiji": {"code": "FJ"},
    "Finland": {"code": "FI"},
    "France": {"code": "FR"},
    "Gabon": {"code": "GA"},
    "Gambia": {"code": "GM"},
    "Georgia": {"code": "GE"},
    "Germany": {"code": "DE"},
    "Ghana": {"code": "GH"},
    "Greece": {"code": "GR"},
    "Grenada": {"code": "GD"},
    "Guatemala": {"code": "GT"},
    "Guinea": {"code": "GN"},
    "Guinea_Bissau": {"code": "GW", "display_name": "Guinea-Bissau"},
    "Guyana": {"code": "GY"},
    "Haiti": {"code": "HT"},
    "Honduras": {"code": "HN"},
    "Hungary": {"code": "HU"},
    "Iceland": {"code": "IS"},
    "India": {"code": "IN"},
    "Indonesia": {"code": "ID"},
    "Iran": {"code": "IR"}, # YouTube'da İran için doğrudan trend verisi kısıtlı olabilir
    "Iraq": {"code": "IQ"},
    "Ireland": {"code": "IE"},
    "Israel": {"code": "IL"},
    "Italy": {"code": "IT"},
    "Jamaica": {"code": "JM"},
    "Japan": {"code": "JP"},
    "Jordan": {"code": "JO"},
    "Kazakhstan": {"code": "KZ"},
    "Kenya": {"code": "KE"},
    "Kiribati": {"code": "KI"},
    "Korea_North": {"code": "KP", "display_name": "Korea (North)"}, # YouTube'da Kuzey Kore için doğrudan trend verisi kısıtlı olabilir
    "Korea_South": {"code": "KR", "display_name": "Korea (South)"},
    "Kosovo": {"code": "XK", "display_name": "Kosovo"}, # ISO 3166-1 alpha-2 standardına dahil değil, dikkat
    "Kuwait": {"code": "KW"},
    "Kyrgyzstan": {"code": "KG"},
    "Laos": {"code": "LA"},
    "Latvia": {"code": "LV"},
    "Lebanon": {"code": "LB"},
    "Lesotho": {"code": "LS"},
    "Liberia": {"code": "LR"},
    "Libya": {"code": "LY"},
    "Liechtenstein": {"code": "LI"},
    "Lithuania": {"code": "LT"},
    "Luxembourg": {"code": "LU"},
    "Madagascar": {"code": "MG"},
    "Malawi": {"code": "MW"},
    "Malaysia": {"code": "MY"},
    "Maldives": {"code": "MV"},
    "Mali": {"code": "ML"},
    "Malta": {"code": "MT"},
    "Marshall_Islands": {"code": "MH", "display_name": "Marshall Islands"},
    "Mauritania": {"code": "MR"},
    "Mauritius": {"code": "MU"},
    "Mexico": {"code": "MX"},
    "Micronesia": {"code": "FM"},
    "Moldova": {"code": "MD"},
    "Monaco": {"code": "MC"},
    "Mongolia": {"code": "MN"},
    "Montenegro": {"code": "ME"},
    "Morocco": {"code": "MA"},
    "Mozambique": {"code": "MZ"},
    "Myanmar": {"code": "MM"},
    "Namibia": {"code": "NA"},
    "Nauru": {"code": "NR"},
    "Nepal": {"code": "NP"},
    "Netherlands": {"code": "NL"},
    "New_Zealand": {"code": "NZ", "display_name": "New Zealand"},
    "Nicaragua": {"code": "NI"},
    "Niger": {"code": "NE"},
    "Nigeria": {"code": "NG"},
    "North_Macedonia": {"code": "MK", "display_name": "North Macedonia"},
    "Norway": {"code": "NO"},
    "Oman": {"code": "OM"},
    "Pakistan": {"code": "PK"},
    "Palau": {"code": "PW"},
    "Palestine": {"code": "PS"},
    "Panama": {"code": "PA"},
    "Papua_New_Guinea": {"code": "PG", "display_name": "Papua New Guinea"},
    "Paraguay": {"code": "PY"},
    "Peru": {"code": "PE"},
    "Philippines": {"code": "PH"},
    "Poland": {"code": "PL"},
    "Portugal": {"code": "PT"},
    "Qatar": {"code": "QA"},
    "Romania": {"code": "RO"},
    "Russia": {"code": "RU"},
    "Rwanda": {"code": "RW"},
    "Saint_Kitts_And_Nevis": {"code": "KN", "display_name": "Saint Kitts and Nevis"},
    "Saint_Lucia": {"code": "LC", "display_name": "Saint Lucia"},
    "Saint_Vincent_And_The_Grenadines": {"code": "VC", "display_name": "Saint Vincent and the Grenadines"},
    "Samoa": {"code": "WS"},
    "San_Marino": {"code": "SM", "display_name": "San Marino"},
    "Sao_Tome_And_Principe": {"code": "ST", "display_name": "Sao Tome and Principe"},
    "Saudi_Arabia": {"code": "SA", "display_name": "Saudi Arabia"},
    "Senegal": {"code": "SN"},
    "Serbia": {"code": "RS"},
    "Seychelles": {"code": "SC"},
    "Sierra_Leone": {"code": "SL", "display_name": "Sierra Leone"},
    "Singapore": {"code": "SG"},
    "Slovakia": {"code": "SK"},
    "Slovenia": {"code": "SI"},
    "Solomon_Islands": {"code": "SB", "display_name": "Solomon Islands"},
    "Somalia": {"code": "SO"},
    "South_Africa": {"code": "ZA", "display_name": "South Africa"},
    "South_Sudan": {"code": "SS", "display_name": "South Sudan"},
    "Spain": {"code": "ES"},
    "Sri_Lanka": {"code": "LK", "display_name": "Sri Lanka"},
    "Sudan": {"code": "SD"},
    "Suriname": {"code": "SR"},
    "Sweden": {"code": "SE"},
    "Switzerland": {"code": "CH"},
    "Syria": {"code": "SY"},
    "Taiwan": {"code": "TW"},
    "Tajikistan": {"code": "TJ"},
    "Tanzania": {"code": "TZ"},
    "Thailand": {"code": "TH"},
    "Togo": {"code": "TG"},
    "Tonga": {"code": "TO"},
    "Trinidad_And_Tobago": {"code": "TT", "display_name": "Trinidad and Tobago"},
    "Tunisia": {"code": "TN"},
    "Turkey": {"code": "TR"},
    "Turkmenistan": {"code": "TM"},
    "Tuvalu": {"code": "TV"},
    "Uganda": {"code": "UG"},
    "Ukraine": {"code": "UA"},
    "United_Arab_Emirates": {"code": "AE", "display_name": "United Arab Emirates"},
    "United_Kingdom": {"code": "GB", "display_name": "United Kingdom"},
    "United_States": {"code": "US", "display_name": "United States"},
    "Uruguay": {"code": "UY"},
    "Uzbekistan": {"code": "UZ"},
    "Vanuatu": {"code": "VU"},
    "Vatican_City": {"code": "VA", "display_name": "Vatican City"},
    "Venezuela": {"code": "VE"},
    "Vietnam": {"code": "VN"},
    "Yemen": {"code": "YE"},
    "Zambia": {"code": "ZM"},
    "Zimbabwe": {"code": "ZW"}
}

# Kıta bazlı ülke listeleri (API'dan veri çekiminde kıta yerine ülke kodu kullanılacak)
# Bu sadece navbarda veya listelemede kıta isimlerini kullanmak için bir mantıksal gruplama.
# API isteği her zaman ülke kodu üzerinden yapılacaktır.
CONTINENT_COUNTRIES = {
    "asia": [
        "Afghanistan", "Armenia", "Azerbaijan", "Bahrain", "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China", "Cyprus", "East_Timor", "Georgia", "India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan", "Kazakhstan", "Kiribati", "Korea_North", "Korea_South", "Kuwait", "Kyrgyzstan", "Laos", "Lebanon", "Malaysia", "Maldives", "Mongolia", "Myanmar", "Nepal", "Oman", "Pakistan", "Palestine", "Philippines", "Qatar", "Saudi_Arabia", "Singapore", "Sri_Lanka", "Syria", "Taiwan", "Tajikistan", "Thailand", "Turkey", "Turkmenistan", "United_Arab_Emirates", "Uzbekistan", "Vietnam", "Yemen"
    ],
    "europe": [
        "Albania", "Andorra", "Austria", "Belarus", "Belgium", "Bosnia_And_Herzegovina", "Bulgaria", "Croatia", "Czech_Republic", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Kosovo", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands", "North_Macedonia", "Norway", "Poland", "Portugal", "Romania", "Russia", "San_Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", "Ukraine", "United_Kingdom", "Vatican_City"
    ],
    "africa": [
        "Algeria", "Angola", "Benin", "Botswana", "Burkina_Faso", "Burundi", "Cabo_Verde", "Cameroon", "Central_African_Republic", "Chad", "Comoros", "Congo_Democratic_RepublicOfThe", "Congo_Republic_Of_The", "Cote_DIvoire", "Djibouti", "Egypt", "Equatorial_Guinea", "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea_Bissau", "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Mali", "Mauritania", "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao_Tome_And_Principe", "Senegal", "Seychelles", "Sierra_Leone", "Somalia", "South_Africa", "South_Sudan", "Sudan", "Tanzania", "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe"
    ],
    "north_america": [
        "Antigua_And_Barbuda", "Bahamas", "Barbados", "Belize", "Canada", "Costa_Rica", "Cuba", "Dominica", "Dominican_Republic", "ElSalvador", "Grenada", "Guatemala", "Haiti", "Honduras", "Jamaica", "Mexico", "Nicaragua", "Panama", "Saint_Kitts_And_Nevis", "Saint_Lucia", "Saint_Vincent_And_The_Grenadines", "Trinidad_And_Tobago", "United_States"
    ],
    "south_america": [
        "Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru", "Suriname", "Uruguay", "Venezuela"
    ],
    "oceania": [
        "Australia", "Fiji", "Kiribati", "Marshall_Islands", "Micronesia", "Nauru", "New_Zealand", "Palau", "Papua_New_Guinea", "Samoa", "Solomon_Islands", "Tonga", "Tuvalu", "Vanuatu"
    ]
}
