# country-data.py

COUNTRY-INFO = {
    "afghanistan": {"code": "af"},
    "albania": {"code": "al"},
    "algeria": {"code": "dz"},
    "andorra": {"code": "ad"},
    "angola": {"code": "ao"},
    "argentina": {"code": "ar"},
    "armenia": {"code": "am"},
    "australia": {"code": "au"},
    "austria": {"code": "at"},
    "azerbaijan": {"code": "az"},
    "bahamas": {"code": "bs"},
    "bahrain": {"code": "bh"},
    "bangladesh": {"code": "bd"},
    "barbados": {"code": "bb"},
    "belarus": {"code": "by"},
    "belgium": {"code": "be"},
    "belize": {"code": "bz"},
    "benin": {"code": "bj"},
    "bhutan": {"code": "bt"},
    "bolivia": {"code": "bo"},
    "bosnia-and-herzegovina": {"code": "ba", "display-name": "bosnia and herzegovina"},
    "botswana": {"code": "bw"},
    "brazil": {"code": "br"},
    "brunei": {"code": "bn"},
    "bulgaria": {"code": "bg"},
    "burkina-faso": {"code": "bf", "display-name": "burkina faso"},
    "burundi": {"code": "bı"},
    "cabo-verde": {"code": "cv", "display-name": "cabo verde"},
    "cambodia": {"code": "kh"},
    "cameroon": {"code": "cm"},
    "canada": {"code": "ca"},
    "central-african-republic": {"code": "cf", "display-name": "central african republic"},
    "chad": {"code": "td"},
    "chile": {"code": "cl"},
    "china": {"code": "cn"}, # youtube'da çin için doğrudan trend verisi kısıtlı olabilir
    "colombia": {"code": "co"},
    "comoros": {"code": "km"},
    "congo-democratic-republicofthe": {"code": "cd", "display-name": "congo (democratic republic of the)"},
    "congo-republic-of-the": {"code": "cg", "display-name": "congo (republic of the)"},
    "costa-rica": {"code": "cr", "display-name": "costa rica"},
    "cote-dıvoire": {"code": "cı", "display-name": "cote d'ıvoire"},
    "croatia": {"code": "hr"},
    "cuba": {"code": "cu"}, # youtube'da küba için doğrudan trend verisi kısıtlı olabilir
    "cyprus": {"code": "cy"},
    "czech-republic": {"code": "cz", "display-name": "czech republic"},
    "denmark": {"code": "dk"},
    "djibouti": {"code": "dj"},
    "dominica": {"code": "dm"},
    "dominican-republic": {"code": "do", "display-name": "dominican republic"},
    "east-timor": {"code": "tl", "display-name": "east timor"},
    "ecuador": {"code": "ec"},
    "egypt": {"code": "eg"},
    "elsalvador": {"code": "sv", "display-name": "el salvador"},
    "equatorial-guinea": {"code": "gq", "display-name": "equatorial guinea"},
    "eritrea": {"code": "er"},
    "estonia": {"code": "ee"},
    "eswatini": {"code": "sz"},
    "ethiopia": {"code": "et"},
    "fiji": {"code": "fj"},
    "finland": {"code": "fı"},
    "france": {"code": "fr"},
    "gabon": {"code": "ga"},
    "gambia": {"code": "gm"},
    "georgia": {"code": "ge"},
    "germany": {"code": "de"},
    "ghana": {"code": "gh"},
    "greece": {"code": "gr"},
    "grenada": {"code": "gd"},
    "guatemala": {"code": "gt"},
    "guinea": {"code": "gn"},
    "guinea-bissau": {"code": "gw", "display-name": "guinea-bissau"},
    "guyana": {"code": "gy"},
    "haiti": {"code": "ht"},
    "honduras": {"code": "hn"},
    "hungary": {"code": "hu"},
    "ıceland": {"code": "ıs"},
    "ındia": {"code": "ın"},
    "ındonesia": {"code": "ıd"},
    "ıran": {"code": "ır"}, # youtube'da iran için doğrudan trend verisi kısıtlı olabilir
    "ıraq": {"code": "ıq"},
    "ıreland": {"code": "ıe"},
    "ısrael": {"code": "ıl"},
    "ıtaly": {"code": "ıt"},
    "jamaica": {"code": "jm"},
    "japan": {"code": "jp"},
    "jordan": {"code": "jo"},
    "kazakhstan": {"code": "kz"},
    "kenya": {"code": "ke"},
    "kiribati": {"code": "kı"},
    "korea-north": {"code": "kp", "display-name": "korea (north)"}, # youtube'da kuzey kore için doğrudan trend verisi kısıtlı olabilir
    "korea-south": {"code": "kr", "display-name": "korea (south)"},
    "kosovo": {"code": "xk", "display-name": "kosovo"}, # ıso 3166-1 alpha-2 standardına dahil değil, dikkat
    "kuwait": {"code": "kw"},
    "kyrgyzstan": {"code": "kg"},
    "laos": {"code": "la"},
    "latvia": {"code": "lv"},
    "lebanon": {"code": "lb"},
    "lesotho": {"code": "ls"},
    "liberia": {"code": "lr"},
    "libya": {"code": "ly"},
    "liechtenstein": {"code": "lı"},
    "lithuania": {"code": "lt"},
    "luxembourg": {"code": "lu"},
    "madagascar": {"code": "mg"},
    "malawi": {"code": "mw"},
    "malaysia": {"code": "my"},
    "maldives": {"code": "mv"},
    "mali": {"code": "ml"},
    "malta": {"code": "mt"},
    "marshall-ıslands": {"code": "mh", "display-name": "marshall ıslands"},
    "mauritania": {"code": "mr"},
    "mauritius": {"code": "mu"},
    "mexico": {"code": "mx"},
    "micronesia": {"code": "fm"},
    "moldova": {"code": "md"},
    "monaco": {"code": "mc"},
    "mongolia": {"code": "mn"},
    "montenegro": {"code": "me"},
    "morocco": {"code": "ma"},
    "mozambique": {"code": "mz"},
    "myanmar": {"code": "mm"},
    "namibia": {"code": "na"},
    "nauru": {"code": "nr"},
    "nepal": {"code": "np"},
    "netherlands": {"code": "nl"},
    "new-zealand": {"code": "nz", "display-name": "new zealand"},
    "nicaragua": {"code": "nı"},
    "niger": {"code": "ne"},
    "nigeria": {"code": "ng"},
    "north-macedonia": {"code": "mk", "display-name": "north macedonia"},
    "norway": {"code": "no"},
    "oman": {"code": "om"},
    "pakistan": {"code": "pk"},
    "palau": {"code": "pw"},
    "palestine": {"code": "ps"},
    "panama": {"code": "pa"},
    "papua-new-guinea": {"code": "pg", "display-name": "papua new guinea"},
    "paraguay": {"code": "py"},
    "peru": {"code": "pe"},
    "philippines": {"code": "ph"},
    "poland": {"code": "pl"},
    "portugal": {"code": "pt"},
    "qatar": {"code": "qa"},
    "romania": {"code": "ro"},
    "russia": {"code": "ru"},
    "rwanda": {"code": "rw"},
    "saint-kitts-and-nevis": {"code": "kn", "display-name": "saint kitts and nevis"},
    "saint-lucia": {"code": "lc", "display-name": "saint lucia"},
    "saint-vincent-and-the-grenadines": {"code": "vc", "display-name": "saint vincent and the grenadines"},
    "samoa": {"code": "ws"},
    "san-marino": {"code": "sm", "display-name": "san marino"},
    "sao-tome-and-principe": {"code": "st", "display-name": "sao tome and principe"},
    "saudi-arabia": {"code": "sa", "display-name": "saudi arabia"},
    "senegal": {"code": "sn"},
    "serbia": {"code": "rs"},
    "seychelles": {"code": "sc"},
    "sierra-leone": {"code": "sl", "display-name": "sierra leone"},
    "singapore": {"code": "sg"},
    "slovakia": {"code": "sk"},
    "slovenia": {"code": "sı"},
    "solomon-ıslands": {"code": "sb", "display-name": "solomon ıslands"},
    "somalia": {"code": "so"},
    "south-africa": {"code": "za", "display-name": "south africa"},
    "south-sudan": {"code": "ss", "display-name": "south sudan"},
    "spain": {"code": "es"},
    "sri-lanka": {"code": "lk", "display-name": "sri lanka"},
    "sudan": {"code": "sd"},
    "suriname": {"code": "sr"},
    "sweden": {"code": "se"},
    "switzerland": {"code": "ch"},
    "syria": {"code": "sy"},
    "taiwan": {"code": "tw"},
    "tajikistan": {"code": "tj"},
    "tanzania": {"code": "tz"},
    "thailand": {"code": "th"},
    "togo": {"code": "tg"},
    "tonga": {"code": "to"},
    "trinidad-and-tobago": {"code": "tt", "display-name": "trinidad and tobago"},
    "tunisia": {"code": "tn"},
    "turkey": {"code": "tr"},
    "turkmenistan": {"code": "tm"},
    "tuvalu": {"code": "tv"},
    "uganda": {"code": "ug"},
    "ukraine": {"code": "ua"},
    "united-arab-emirates": {"code": "ae", "display-name": "united arab emirates"},
    "united-kingdom": {"code": "gb", "display-name": "united kingdom"},
    "united-states": {"code": "us", "display-name": "united states"},
    "uruguay": {"code": "uy"},
    "uzbekistan": {"code": "uz"},
    "vanuatu": {"code": "vu"},
    "vatican-city": {"code": "va", "display-name": "vatican city"},
    "venezuela": {"code": "ve"},
    "vietnam": {"code": "vn"},
    "yemen": {"code": "ye"},
    "zambia": {"code": "zm"},
    "zimbabwe": {"code": "zw"}
}
