[functions]
directory = "netlify/functions"

# FONKSİYON İSTEKLERİNİ HER ŞEYDEN ÖNCE İŞLE
[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200

# Diğer tüm kurallar bundan sonra gelmeli
[[redirects]]
from = "/ads.txt"
to = "/ads.txt"
status = 200

[[redirects]]
from = "http://toptubelist.com/*"
to = "https://www.toptubelist.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://toptubelist.com/*"
to = "https://www.toptubelist.com/:splat"
status = 301
force = true

# En genel kural en sonda olmalı
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
