[functions]
directory = "netlify/functions"


[[redirects]]
from = "/ads.txt"
to = "/ads.txt"
status = 200

[[redirects]]
from = "http://toptubelist.com/*"
to = "https://www.toptubelist.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://toptubelist.com/*"
to = "https://www.toptubelist.com/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
