[functions]
directory = "netlify/functions"

# Functions rotaları SPA redirect'e takılmasın
[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/ads.txt"
to = "/ads.txt"
status = 200

[[redirects]]
from = "http://toptubelist.com/*"
to = "https://www.toptubelist.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://toptubelist.com/*"
to = "https://www.toptubelist.com/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
