name: Generate and Update Country YouTube Data

on:
  schedule:
    # Her 3 saatte bir çalışır. UTC saat dilimine göre ayarlanır.
    # Örneğin, 00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00, 21:00 UTC saatlerinde çalışır.
    - cron: '0 */3 * * *'
  
  # Manuel olarak çalıştırma butonu ekler
  workflow_dispatch:

jobs:
  update-youtube-data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Kullandığınız Python sürümünü buraya yazın (örn. 3.8, 3.9, 3.10, 3.11, 3.12)
        cache: 'pip' # pip bağımlılıklarını önbelleğe al, sonraki çalıştırmaları hızlandırır

    - name: Install dependencies
      run: |
        # Python betiğinizin ihtiyaç duyduğu pip paketlerini buraya ekleyin
        # 'requests' kütüphanesi mutlaka gerekli olacaktır.
        pip install requests

    - name: Run Python script
      env:
        # YouTube Data API anahtarınızı GitHub Secrets'tan alır.
        # Bu anahtarı deponuzun ayarlarına (Settings -> Secrets and variables -> Actions) eklemelisiniz.
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        python generate_country_youtube_data.py
    
    # Oluşturulan/güncellenen JSON ve HTML dosyalarını depoya geri gönder (commit ve push)
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add *.json *.html # Sadece .json ve .html uzantılı dosyaları ekle
        git commit -m "Otomatik YouTube verileri güncellemesi" || echo "Değişiklik yok, commit atlanıyor."
        git push
      # Bu adım sadece değişiklikler varsa commit yapacaktır.
      # "|| echo "Değişiklik yok, commit atlanıyor."" kısmı, değişiklik olmadığında hata vermesini engeller.
