name: Delete Folders
on:
  workflow_dispatch:  # Manuel tetikleme için
    inputs:
      folders:
        description: "Silinecek klasörler (virgülle ayırın, örn: 'temp/,docs/')"
        required: true
      commit_message:
        description: "Commit mesajı"
        default: "GitHub Action ile klasörler silindi"
        
jobs:
  delete-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Tüm commit geçmişini al

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run folder deletion script
        run: |
          python -c "
          import subprocess
          folders = '${{ github.event.inputs.folders }}'.split(',')
          for folder in folders:
              subprocess.run(['git', 'rm', '-r', '--cached', folder.strip()], check=True)
          subprocess.run(['git', 'commit', '-m', '${{ github.event.inputs.commit_message }}'], check=True)
          subprocess.run(['git', 'push'], check=True)
          "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Otomatik auth için
