name: Generate Countries JSON

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run script to generate countries.json
      run: python generate_country_buttons_json.py

    - name: Output debug
      run: cat output/countries.json

    - name: Upload countries.json as artifact
      uses: actions/upload-artifact@v4
      with:
        name: countries-json
        path: output/countries.json
