name: Generate Continent Pages

on:
  push:
    branches:
      - main # Or your default branch, e.g., master
    paths:
      - '**.py' # Run if any Python file changes
      - 'data/*.json' # Run if any data JSON changes
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub UI

jobs:
  build-pages:
    runs-on: ubuntu-latest # Or 'macos-latest', 'windows-latest' if preferred

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies (if any)
      run: |
        # If your script had external dependencies (e.g., 'requests'), you'd list them in requirements.txt
        # python -m pip install --upgrade pip
        # pip install -r requirements.txt
        echo "No specific Python dependencies to install."

    - name: Create necessary directories (if they don't exist)
      run: |
        mkdir -p continents/asia
        mkdir -p continents/europe
        mkdir -p continents/africa
        mkdir -p continents/north-america
        mkdir -p continents/south-america
        mkdir -p continents/oceania
        mkdir -p data # Ensure data directory exists for JSON files

    - name: Run Python script to generate HTML
      run: python your_script_name.py # Replace 'your_script_name.py' with the actual name of your Python file

    - name: Upload generated pages as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: continent-pages
        path: continents/
        retention-days: 5 # How long to keep the artifact

    - name: Deploy to GitHub Pages (optional, if you're hosting this way)
      # This step assumes you want to deploy the generated 'continents' folder
      # and potentially other HTML files (like index.html) to GitHub Pages.
      # You'll need to adjust 'build_directory' if your Python script outputs
      # directly to the root or another specific folder that GitHub Pages serves.
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }} # Deploy only from the main branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # This will publish everything in the root of the repo.
                        # If you only want to publish the 'continents' directory,
                        # you might need to structure your repo differently or
                        # adjust this to 'continents'.
                        # For your current structure, you might want to move
                        # 'assets' and 'index.html' into a 'build' folder,
                        # and then publish that 'build' folder.
                        # For simplicity, if your whole site is generated,
                        # 'build_directory: .' works if everything is at the root.
