name: Generate All Youtube Data

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-videos:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Gerekli paketleri kur
        run: pip install requests python-dotenv

      - name: API key'i yükle
        run: echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" >> $GITHUB_ENV

      - name: Python script'i çalıştır
        run: python generate_youtube_data.py

      - name: Git ayarla ve değişiklikleri gönder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add countries_html/*.json
          git commit -m "Güncellenmiş YouTube verisi [skip ci]" || echo "Değişiklik yok"
          git push
