name: Rename Files and Folders

on:
  push:
    branches:
      - main  # Sadece main branch'ine push yapıldığında çalışsın
  schedule:
    - cron: '0 3 * * *'  # Her gün saat 03:00'te çalıştır (Opsiyonel)

jobs:
  rename:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Run Rename Script
        run: |
          python rename_files.py
        env:
          ROOT_DIR: "."  # Kök dizini belirt (proje klasörü)
