name: Rename Files and Folders

on:
  push:
    branches:
      - main  # Sadece main'e push yapıldığında çalışsın
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  rename_files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Dosya adlarını değiştirmek için yazma izni

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Repoyu al

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Python versiyonu

      - name: Run Rename Script
        run: python rename_files.py  # Betiği çalıştır
