name: Standardize JSON / structured Filenames

on:
  workflow_dispatch: # Manuel başlatılabilir
  schedule:
    - cron: '0 0 * * *' # Her gün UTC gece yarısı (Türkiye'de 03:00)

jobs:
  rename_json_files:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Dışarı Çek
      uses: actions/checkout@v4

    - name: Python Ortamını Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Dosya Adı Standardizasyon Betiğini Çalıştır
      run: python rename_country_data.py

    - name: Değişiklikleri Kontrol Et
      id: git_status
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # SADECE structured_data klasörünü ekle
        git add Country_data/structured_data/

        if git diff --staged --quiet; then
          echo "no_changes=true" >> "$GITHUB_OUTPUT"
        else
          echo "no_changes=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Değişiklikleri Kaydet ve Push Et
      if: steps.git_status.outputs.no_changes == 'false'
      run: |
        git commit -m "Refactor: Standart structured_data JSON dosya adları (otomatik)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
