name: Update videos and structured data every 3 hours

on:
  schedule:
    - cron: '0 */3 * * *'  # Her 3 saatte bir
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bağımlılıkları yükle (eğer gerekiyorsa)
        run: |
          pip install -r requirements.txt || true

      - name: fetch_top_youtube.py dosyasını çalıştır
        run: |
          python fetch_top_youtube.py

      - name: Değişiklikleri commit et ve pushla
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔄 Otomatik update: videos.json, structured_data.json ve index.html" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Bayjeolog35/TopTubeList.git
