name: Update Country YouTube Data
on:
  schedule:
    - cron: '0 */3 * * *'  # Her 3 saatte bir çalıştır
  workflow_dispatch:  # Manuel çalıştırma için

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 python-dotenv
        
    - name: Run script
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        python country_youtube_data.py
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-update video data" || echo "No changes to commit"
        git push
